name: Update Brew Repository
description: Updates the Homebrew tap repository with new release information

inputs:
  version:
    description: Version number to distribute
    required: true
  token:
    description: Token for accessing the Homebrew tap repository
    required: true
  tap_repo:
    description: Homebrew tap repository name
    required: false # Optional, defaults can be inferred if needed
  extension_info_json:
    description: JSON string containing extension info (name, version, url, sha256)
    required: true

runs:
  using: composite
  steps:
    - name: Get Release Info
      id: release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }} # Use the input token here
      run: |
        # Get release info with URLs
        echo "Fetching release info for ${{ inputs.version }}..."
        gh release view "${{ inputs.version }}" --json assets > release.json
        if [ $? -ne 0 ]; then echo "Error: Failed to fetch release info."; exit 1; fi
        echo "Release info saved to release.json"

        # Get x86_64 binary info (URL) - Find the binary directly, not tar.gz
        echo "Extracting Intel URL..."
        INTEL_BINARY_NAME="icp-x86_64-apple-darwin-homebrew"
        INTEL_URL=$(jq -r --arg name "$INTEL_BINARY_NAME" '.assets[] | select(.name == $name) | .url' release.json)
        if [ -z "$INTEL_URL" ] || [ "$INTEL_URL" == "null" ]; then echo "Error: Intel URL ($INTEL_BINARY_NAME) not found in release assets."; exit 1; fi
        echo "intel_url=$INTEL_URL" >> $GITHUB_OUTPUT
        echo "Intel URL: $INTEL_URL"

        # Get ARM binary info (URL) - Find the binary directly, not tar.gz
        echo "Extracting ARM URL..."
        ARM_BINARY_NAME="icp-aarch64-apple-darwin-homebrew"
        ARM_URL=$(jq -r --arg name "$ARM_BINARY_NAME" '.assets[] | select(.name == $name) | .url' release.json)
        if [ -z "$ARM_URL" ] || [ "$ARM_URL" == "null" ]; then echo "Error: ARM URL ($ARM_BINARY_NAME) not found in release assets."; exit 1; fi
        echo "arm_url=$ARM_URL" >> $GITHUB_OUTPUT
        echo "ARM URL: $ARM_URL"

        # Download individual checksum files
        echo "Downloading checksum files..."
        INTEL_SHA_FILE="${INTEL_BINARY_NAME}.sha256"
        ARM_SHA_FILE="${ARM_BINARY_NAME}.sha256"
        gh release download "${{ inputs.version }}" --pattern "$INTEL_SHA_FILE" --output "$INTEL_SHA_FILE"
        if [ $? -ne 0 ]; then echo "Error: Failed to download $INTEL_SHA_FILE."; exit 1; fi
        gh release download "${{ inputs.version }}" --pattern "$ARM_SHA_FILE" --output "$ARM_SHA_FILE"
        if [ $? -ne 0 ]; then echo "Error: Failed to download $ARM_SHA_FILE."; exit 1; fi

        # Extract checksums from files
        echo "Extracting checksums from files..."
        INTEL_SHA=$(cat "$INTEL_SHA_FILE" | cut -d ' ' -f 1) # Get first field in case of extra whitespace/filename
        if [ -z "$INTEL_SHA" ]; then echo "Error: Could not read Intel SHA256 from $INTEL_SHA_FILE."; exit 1; fi
        echo "intel_sha256=$INTEL_SHA" >> $GITHUB_OUTPUT
        echo "Intel SHA256: $INTEL_SHA"

        ARM_SHA=$(cat "$ARM_SHA_FILE" | cut -d ' ' -f 1) # Get first field
        if [ -z "$ARM_SHA" ]; then echo "Error: Could not read ARM SHA256 from $ARM_SHA_FILE."; exit 1; fi
        echo "arm_sha256=$ARM_SHA" >> $GITHUB_OUTPUT
        echo "ARM SHA256: $ARM_SHA"

    - name: Clone Tap Repository
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git clone "https://x-access-token:${{ inputs.token }}@github.com/${{ inputs.tap_repo }}.git" tap-repo

    - name: Write Extension Info to File
      shell: bash
      run: |
        echo "Writing extension info JSON to hb_ext_info.json..."
        echo '${{ inputs.extension_info_json }}' > hb_ext_info.json
        if [ $? -ne 0 ]; then echo "Error: Failed to write hb_ext_info.json"; exit 1; fi
        echo "Contents of hb_ext_info.json:"
        cat hb_ext_info.json

    - name: Generate Formula
      shell: bash
      run: |
        # Generate formula using our tool, passing the path to the extension JSON file
        cargo run --package icp-distribution --bin generate_formula -- \
          --version "${{ inputs.version }}" \
          --extension-info-path hb_ext_info.json \ # Pass path to the JSON file
          --intel-url "${{ steps.release.outputs.intel_url }}" \
          --intel-sha256 "${{ steps.release.outputs.intel_sha256 }}" \
          --arm-url "${{ steps.release.outputs.arm_url }}" \
          --arm-sha256 "${{ steps.release.outputs.arm_sha256 }}" \
          --output tap-repo/Formula/icp-cli.rb

    - name: Commit and Push Changes
      shell: bash
      working-directory: tap-repo
      run: |
        git add Formula/icp-cli.rb
        git commit -m "Update icp-cli to version ${{ inputs.version }}"
        git push

    - name: Cleanup Temporary Files
      shell: bash
      run: |
        echo "Cleaning up temporary files..."
        rm -f release.json *.sha256 hb_ext_info.json # Remove downloaded release info, checksum files, and temp JSON
        echo "Cleanup complete."
