[package]
name = "test-utils"
version.workspace = true
edition = "2021"

[dependencies]
anyhow = { workspace = true }
wasmtime = { workspace = true }
tokio = { workspace = true }
icp-core = { path = "../icp-core" }

[dev-dependencies]
tokio-test = { workspace = true }
