[guidelines]
active = [
    "pm",
    "codebase-purpose",
    "extension-development",
    "coding",
    "testing",
    "vcs",
    "detailed-content-preference",
    "ambiguity-resolution",
    "guideline-management",
    "release-process",
]
