[package]
name = "icp-component-invoke"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
wasmtime = { workspace = true, optional = true }

[features]
default = []
wasmtime-conversions = ["dep:wasmtime"]
