name: Update quick-install
description: Update quick-install

inputs:
  version:
    description: Version number to distribute
    required: true

  token:
    description: GitHub token for authentication
    required: true

  extension_info_json:
    description: JSON string containing info for latest extensions
    required: true

runs:
  using: composite
  steps:
    - name: Download ICP Binaries and Checksums using Glob Patterns
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        echo "Downloading binaries and checksums for ${{ inputs.version }}..."
        mkdir -p dist/binaries/icp # Ensure target directory exists

        echo "Downloading binaries matching 'icp-*'..."
        # Download binaries - use a pattern that excludes .sha256 if possible, or handle potential extra files later
        # Using a simple 'icp-*' pattern for now. Might need refinement if other 'icp-*' files exist.
        gh release download "${{ inputs.version }}" --dir dist/binaries/icp --pattern "icp-*" --clobber
        if [ $? -ne 0 ]; then echo "Warning: Failed to download binaries matching 'icp-*'."; fi

        echo "Download using 'icp-*' pattern complete."
        echo "Contents of dist/binaries/icp:"
        ls -l dist/binaries/icp

    - name: Write Extension Info to File
      shell: bash
      run: |
        echo "Writing extension info JSON to extension_info.json..."
        echo '${{ inputs.extension_info_json }}' > extension_info.json
        if [ $? -ne 0 ]; then echo "Error: Failed to write extension_info.json"; exit 1; fi
        echo "Contents of extension_info.json:"
        cat extension_info.json

    - name: Generate scripts
      shell: bash
      run: |
        cargo run --bin generate_scripts -- \
          --binary-path dist/binaries/icp \
          --output-dir dist \
          --domain "${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}" \
          --repo-url "https://github.com/${GITHUB_REPOSITORY}" \
          --extension-info-path extension_info.json # Pass path to the JSON file

    - name: Clean up Temporary File
      if: always() # Ensure cleanup happens even if previous steps fail
      shell: bash
      run: |
        echo "Removing temporary file extension_info.json..."
        rm -f extension_info.json

    - name: Check Generated Files # Renamed for clarity
      shell: bash
      run: |
        required_files=("install.sh" "install.ps1" "index.html" ".nojekyll")
        for file in "${required_files[@]}"; do
          if [ ! -f "dist/$file" ]; then
            echo "Error: Required file $file not found"
            exit 1
          fi
        done

    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: gh-pages
        clean: true
