name: Update Distribution Channels

on:
  workflow_dispatch:

concurrency:
  group: distribution-update
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cli_version: ${{ steps.get-cli-version.outputs.cli_version }}
      extension_info_json: ${{ steps.get-extensions.outputs.extension_info }}

    permissions:
      contents: read
      actions: read

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch Latest CLI Release Tag
        id: get-cli-version
        run: |
          # Fetch the latest tag matching v*.*.* pattern
          LATEST_CLI_TAG=$(gh release list --repo ${{ github.repository }} --limit 10 --exclude-drafts --exclude-pre-releases --json tagName --jq '.[] | select(.tagName | startswith("v")) | .tagName' | head -n 1)
          if [ -z "$LATEST_CLI_TAG" ]; then
            echo "Error: Could not determine latest CLI release tag."
            exit 1
          fi
          echo "Latest CLI Tag: $LATEST_CLI_TAG"
          echo "cli_version=$LATEST_CLI_TAG" >> $GITHUB_OUTPUT

      - name: Get Latest Extension Info
        id: get-extensions
        uses: ./.github/actions/fetch-latest-extensions
        with:
          extensions: "build identity project" # Define which extensions to include
          github_token: ${{ env.GH_TOKEN }}

  quick-install:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for gh-pages deployment
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Call Quick Install Action
        uses: ./.github/actions/distribution/quick-install
        with:
          version: ${{ needs.setup.outputs.cli_version }}
          token: ${{ env.GH_TOKEN }}
          extension_info_json: ${{ needs.setup.outputs.extension_info_json }}

  homebrew:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Call Homebrew Action
        uses: ./.github/actions/distribution/homebrew
        with:
          version: ${{ needs.setup.outputs.cli_version }}
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          tap_repo: ${{ github.repository_owner }}/homebrew-icp-cli
          extension_info_json: ${{ needs.setup.outputs.extension_info_json }}
