name: Publish WIT Packages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish WIT Packages using Composite Action
        uses: ./.github/actions/wit/publish
        with:
          ghcr_pat: ${{ secrets.GHCR_PAT_TOKEN }}
