package icp:cli@0.3.3;

interface cli {
  // spec provides a schema a for the cli
  spec: func() -> string;

  // run the cli portion of the extension
  run: func(args: list<string>) -> u8;
}

interface init {
  init: func() -> result<_, string>;
}

world extension {
  import misc;
  import filesystem;
  import component;

  export init;
  export cli;
}
