package icp:cli@0.3.4;

// This package defines the interfaces and world for ICP CLI extensions.
// Extensions import interfaces from the `icp:cli` package to interact with the CLI host.

/// The `extension` world defines the set of interfaces that an ICP CLI
/// extension component is expected to import and export.
world extension {
  import command;
  import component;
  import filesystem;
  import misc;

  export init;
  export cli;
}

/// The `cli` interface defines the functions that an extension must export
/// to provide CLI functionality.
interface cli {
  // spec provides a schema for the cli subcommand's arguments and help text.
  spec: func() -> string;

  // run the cli portion of the extension
  run: func(args: list<string>) -> u8;
}

/// The `init` interface defines the initialization function for an extension.
interface init {
  /// The initialization function is called by the host after the extension
  /// component has been instantiated.
  init: func() -> result<_, string>;
}
